Rearrange the repository

diff --git a/test_Colleen b/test_Colleen
--- a/test_Colleen
+++ b/test_Colleen
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
-COLLEEN_SRC="$1"
-
-if [ -z "$COLLEEN_SRC" ]; then
-	COLLEEN_SRC="Colleen.c"
+if [ -z "$1" ]; then
+	echo "error: no argument provided"
+	exit 1
 fi
 
-COLLEEN_EXEC="${COLLEEN_SRC%.*}"
+COLLEEN_SRC="$1"
+COLLEEN_EXEC=$(basename ${COLLEEN_SRC%.*})
 OUT_FILE="tmp_$COLLEEN_EXEC"
 
 if ! gcc -Wall -Wextra -Werror -o "$COLLEEN_EXEC" "$COLLEEN_SRC"; then
