Clean ASM Sully

diff --git a/templates/set_source_code_str b/templates/set_source_code_str
--- a/templates/set_source_code_str
+++ b/templates/set_source_code_str
@@ -12,31 +12,31 @@ if [ -z "$1" ]; then
 fi
 
 case "$1" in
-		'TEMPLATE_ColleenV1.c')
-				echo 'const char	*g_source_code[] = {' > "$SELF_REP_COPY"
-				LQUOTE='	"'
-				RQUOTE='\n",'
-				;;
-		'TEMPLATE_Colleen.c')
-				echo 'char*t[]={' > "$SELF_REP_COPY"
-				echo '"char*t[]={",' >> "$SELF_REP_COPY"
-				echo '"0};",' >> "$SELF_REP_COPY"
-				LQUOTE='"'
-				RQUOTE='",'
-				;;
-		'TEMPLATE_Colleen.s' | 'TEMPLATE_Grace.s')
-				cat "$TARGET_CODE" > "$SELF_REP_COPY"
-				LEN="$(wc -l "$TARGET_CODE" | awk '{print $1}')"
-				LEN="$(echo 'obase=16;'$LEN'+2' | bc)"
-				echo "TXT_LINE_COUNT equ 0x"$LEN >> "$SELF_REP_COPY"
-				echo "txt:" >> "$SELF_REP_COPY"
-				LQUOTE='db "'
-				RQUOTE='", 0x0'
-				;;
-		*)
-				echo "error: invalid argument"
-				exit 1
-				;;
+	'TEMPLATE_ColleenV1.c')
+		echo 'const char	*g_source_code[] = {' > "$SELF_REP_COPY"
+		LQUOTE='	"'
+		RQUOTE='\n",'
+		;;
+	'TEMPLATE_Colleen.c')
+		echo 'char*t[]={' > "$SELF_REP_COPY"
+		echo '"char*t[]={",' >> "$SELF_REP_COPY"
+		echo '"0};",' >> "$SELF_REP_COPY"
+		LQUOTE='"'
+		RQUOTE='",'
+		;;
+	'TEMPLATE_Colleen.s' | 'TEMPLATE_Grace.s' | 'TEMPLATE_Sully.s')
+		cat "$TARGET_CODE" > "$SELF_REP_COPY"
+		LEN="$(wc -l "$TARGET_CODE" | awk '{print $1}')"
+		LEN="$(echo 'obase=16;'$LEN'+2' | bc)"
+		echo "TXT_LINE_COUNT equ 0x"$LEN >> "$SELF_REP_COPY"
+		echo "txt:" >> "$SELF_REP_COPY"
+		LQUOTE='db "'
+		RQUOTE='", 0x0'
+		;;
+	*)
+		echo "error: invalid argument"
+		exit 1
+		;;
 esac
 
 while read; do
@@ -44,17 +44,20 @@ while read; do
 done < "$TARGET_CODE"
 
 case "$1" in
-		'TEMPLATE_ColleenV1.c')
-				echo '	0' >> "$SELF_REP_COPY"
-				echo '};' >> "$SELF_REP_COPY"
-				cat "$TARGET_CODE" >> "$SELF_REP_COPY"
-				;;
-		'TEMPLATE_Colleen.c')
-				echo '0};' >> "$SELF_REP_COPY"
-				cat "$TARGET_CODE" >> "$SELF_REP_COPY"
-				;;
-		'TEMPLATE_Colleen.s' | 'TEMPLATE_Grace.s')
-				echo 'db "TXT_LINE_COUNT equ 0x'$LEN'", 0x0' >> "$SELF_REP_COPY"
-				echo 'db "txt:", 0x0' >> "$SELF_REP_COPY"
-				;;
+	'TEMPLATE_ColleenV1.c')
+		echo '	0' >> "$SELF_REP_COPY"
+		echo '};' >> "$SELF_REP_COPY"
+		cat "$TARGET_CODE" >> "$SELF_REP_COPY"
+		;;
+	'TEMPLATE_Colleen.c')
+		echo '0};' >> "$SELF_REP_COPY"
+		cat "$TARGET_CODE" >> "$SELF_REP_COPY"
+		;;
+	'TEMPLATE_Colleen.s' | 'TEMPLATE_Grace.s' | 'TEMPLATE_Sully.s')
+		echo 'db "TXT_LINE_COUNT equ 0x'$LEN'", 0x0' >> "$SELF_REP_COPY"
+		echo 'db "txt:", 0x0' >> "$SELF_REP_COPY"
+		if [ "$1" = 'TEMPLATE_Sully.s' ]; then
+			echo 'INTEGER dq 5' >> "$SELF_REP_COPY"
+		fi
+		;;
 esac
